'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1022
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WinApp_BCalc.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property ABC05_Banner() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ABC05 Banner", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property basketball1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("basketball1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bck() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bck", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bckg66() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bckg66", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bckgd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bckgd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bckgrnd5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bckgrnd5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bkggif() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bkggif", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BvPoisson() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BvPoisson", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BvPoissonL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BvPoissonL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property eXchange() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eXchange", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property eXchangeL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eXchangeL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property football1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("football1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FrontLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FrontLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Kelly1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Kelly1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Kelly2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Kelly2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Kelly3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Kelly3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LangCro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LangCro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LangEn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LangEn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LogoFront() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LogoFront", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Misc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Misc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MiscL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MiscL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MultiKelly() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MultiKelly", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MultiKellyL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MultiKellyL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Racing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Racing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RacingL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RacingL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property redarrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redarrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Systems() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Systems", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SystemsL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SystemsL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TBall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TBall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tennis() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tennis", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tennis1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tennis1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tennis2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tennis2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TennisL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TennisL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property untitled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("untitled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WinCalc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WinCalc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WinCalcL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WinCalcL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
